### ISSUE TITLE
ALTERNATIVE_OBJECTIVE - chyba zanesená v Pull Request 7

### ISSUE THREAD

**Issue by celerini** [hrubymar10/wesnoth-cs#15]
https://github.com/hrubymar10/wesnoth-cs/blob/8cd4b45515cf5ea48018604656be5a6eb7212414/wesnoth-ei.po#L2644-L2648

@MultiSeptim

Trochu jsem to zkoumal a zdá se, že se nejedná o chybu v originále, ale chybu v našem překladu.

Hra už by teď NEBO měla vypsat sama a alternativní cíl je přeložen jinde (na řádku 499 - nad ním je poznámka, že se použije i v S12 - Evacuation).

Vizte [commit](https://github.com/wesnoth/wesnoth/commit/3c1dd4d55593e2fa8ec0cf80768745aeaf1f7126).

Rád bych, abychom se na tom shodli, než to jeden z nás opraví.

**Comment by MultiSeptim** [comment]
Nález se zdá být správný. Opravím to.

**Comment by celerini** [comment]
opraveno v #17
