### ISSUE TITLE
Semenáček kontra Sazenek

### ISSUE THREAD

**Issue by celerini** [hrubymar10/wesnoth-cs#16]
https://github.com/hrubymar10/wesnoth-cs/blob/8cd4b45515cf5ea48018604656be5a6eb7212414/wesnoth-units.po#L7493-L7494

@MultiSeptim 

Když jsem zahrnul váš překlad Wose Sapling jako Sazenek, upozornila mne dcera, že v TRoW je použit výraz Semenáček. Abych to sladil, tak jsem se jal zkoumat a zjistil:

Sapling je mladý stromek do 10 cm v průměru.
Sazenek není podle Google normálně používané slovo.
Semenáček je něco hodně malého (ještě má děložní lístky).
[Obrázky a texty hry](https://units.wesnoth.org/1.15/mainline/en_US/Wose%20Sapling.html) naznačují, že se opravdu jedná o mladší strom, ale ne o sazeničku.
Český překlad Wose sleduje linii Stromový muž.

Když jsem to dal dohromady, vyšel mi Stromový mladík.

Vzdáte se Sazenka nebo za něj chcete bojovat?

**Comment by MultiSeptim** [comment]
No u Wose se zatím "jede" jen mužská linie. Ale nevím, možná je jen otázka času, kdy dojde k genderovému narovnání :-). Pak by mi přišla Sazenka jako pěkný termín (rozhodně víc než jen Stromová mladice apod.).
Takto jsem tak trochu uvažoval, když jsem Sazenka generoval.

Líbí se mi a rád bych za něj bojoval.

**Comment by hrubymar10** [comment]
No... Já bych byl spíš na straně @celerini a podpořil tedy verzi "Stromový mladík".

Možná bych navrhl ještě další variaty (některé né moc vážně míněné):
* Stromový teenager
* Stromové nedochůdče
* Stromový mladý
* Mladý strom
* Mladý stromů

Možná by se také dalo předělat celou "Wose" linii gendrově neutrálně a pak by mi vyšlo třeba:
* Wose - Stromor (ano, je to naprosto vymyšlené slovo bez jakýchkoliv jazykových základů (teda kromě toho že obsahuje slovo strom)...)
* Wose Sapling - Mladý stromor
* Wose Shaman - Šamanský stromor

Když bych si neměl vymýšlet slova, tak díky trilogii pána prstenů byla až počeštěno slovo ["Ent"](https://cs.wikipedia.org/wiki/Enti), čili s ním stvořit podobné tvary jako u stromora.

Upozorňuji, že jsem dneska nevstal správnou nohou, takže pokud jsem vymyslel naprostou blbost, tak se moc omlouvám 😃

**Comment by MultiSeptim** [comment]
Já si myslím, že je škoda, že se hezké slovo Ent nepoužilo. Když už se to vžilo...
Prostě se šlo cestou takového ne elegantního opisování ve stylu Stromový muž atd. Což vždycky to bude znít jako náhražka. Jestli tedy budeme ochotni do toho radikálněji šlápnout, jsem za to použít enty.

**Comment by celerini** [comment]
Včera jsem se v duchu smiřoval s tím Sazenkem a vy dnes takhle.

Motivem mého prvního příspěvku bylo sjednocení překladu. Nezáleží mi až tak na jediném slově, máme jich tam k opravě a překladu ještě dost.

Na Sazenkovi mi stále vadí, že tolik vybočuje z řady českého překladu Wose. Kvůli soudržnosti překladu by bylo od Septima poctivé, aby vymyslel pro každého jednotlivého Wose jiný český novotvar, ale to je myslím zbytečné úsilí.

Co se týče Entů, nejsou ve hře [schválně](https://forums.wesnoth.org/viewtopic.php?f=7&t=42413). Ne že by to všichni překladatelé respektovali. Já toho jediného (Entího šamana v DM) postromil loni v prosinci.

Ohledně překladu Wose mne napadlo, že nám překáží to, že nemáme v pohádkách žádnou takovou postavu. Jenom hejkala. Němci mají třeba svého [Waldschrata](https://de.wikipedia.org/wiki/Schrat).

Díval jsem se, jak překládají jiní - bratři Slováci mají lesného muža, Poláci drzewieca, Rusové dreveně (Древень)...

Zaujal mne ukrajinský [Лісовик](https://uk.wikipedia.org/wiki/%D0%9B%D1%96%D1%81%D0%BE%D0%B2%D0%B8%D0%BA), ze kterého vede odkaz na český překlad [Lešij](https://cs.wikipedia.org/wiki/Le%C5%A1ij). Stojí tam, že je to východoslovanský rodák, my máme [divé lidi](https://cs.wikipedia.org/wiki/Div%C3%AD_lid%C3%A9). A už jsem zpátky u svého [hejkala](https://cs.wikipedia.org/wiki/Hejkal). Jenže ti wesnotští Wosové moc nehýkají.

Takže kdybych já teď měl měnit český překlad Wose, tak bych použil Stromous. Dost připomíná Tolkienova Enta Stromovouse, ale je kratší, tak trochu vystihuje podstatu (strom a vousatý chlapík), je příbuzný s Martinovým Stromorem (ten mi ale připadá dost morbidní), rýmuje se na Wose, je to podle vzoru divous (zpátky k divým lidem) a je to jedno slovo.

K přívlastkům bych už jiná slova nehledal.

Mladý stromous
Stromous
Starý stromous
Prastarý stromous
Stromous šaman

Na to, jak jsem se tím nechtěl moc zabývat, jsem trochu ulétl. Věřím, že mne dokážete vrátit na zem.

**Comment by MultiSeptim** [comment]
Stromous? To se mi líbí! Je to takové etymologicky fajnové...

**Comment by hrubymar10** [comment]
> Stromous? To se mi líbí! Je to takové etymologicky fajnové...

Má přítelkyně sice konstatovala, že vazba na Tolkienova Enta Stromovouse se jí moc nelíbí a proto by hlasovala spíš pro `Stromora` (nebo nějakou jinou alternativu), ale na druhou stranu si nemyslím, že to z toho kouká tak moc. Chci tím naznačit, že pokud hru nebude hrát člověk, který onu trilogii vyloženě "žere", tak si této asociace nevšimne.

Čili za mne ok a hlasuji pro předělání všech "Wosů" na "Stromouse".

**Comment by celerini** [comment]
Díky za reakce na stromouse.

Jen nerozumím tomu, Martine, jak to s přítelkyní myslíte, když se jí nelíbí vazba a vám kouká asociace. Rád bych to pochopil, než začnu něco měnit.

Možná jsem se nepřesně vyjádřil. Wesnothští wosové **jsou** Tolkienovi enti (o čemž svědčí text v nápovědě a Delfador ve svých pamětech), jen se tak nemají nebo nesmí jmenovat (nevím přesně proč). Proto můj návrh schválně používá zkrácený doslovný překlad jména nejstaršího z entů do češtiny, čímž se pokouší trochu narovnat stav a tak trochu pomrkává (víme, jak to je). Takže za mne je ta vazba v pořádku a ukazuje správným směrem – potvrzuje, co je zjevné.

Koncovka -or ve stromorovi se mi líbí (jako sochor), ale díky -m v kořeni stromu tam slyším i vidím mor, což ve mně vyvolává nepříjemné představy nemoci, zmaru – jako hladomor nebo Mrakomor. Nezavrhuji ho, jen bych si na něj musel déle zvykat.

Mé poradkyni se nejvíc líbí stromový muž a vůbec jí nevadí, že je to opis. Důležité pro ni je, že je to česky.

Abych se vrátil k předmětu diskuse – rozumím tomu správně, že oba shodně navrhujete znovu přeložit všechny Wose, abychom vyřešili schizma Semenáček x Sazenek?

Já se spokojím i s menší změnou, jen když povede ke sjednocení překladu. Wose můžeme nechat uležet...

**Comment by MultiSeptim** [comment]
Jasně. Když už jsme se donutili k takové diskuzi (recenzované), tak ať má větší výsledky, než jen název jedné jednotky.

**Comment by MultiSeptim** [comment]
Ještě bych chtěl trochu na obraj podotknout, že si myslím, že není obecně nutné, aby byly jednotky vždy přeloženy nějak jednotně ve stylu: Mladý X - X - Starý (zkušený) X.
Některé národy to porušují. Typicky je to u lidí (protože národy jsou ve Wesnothu asi pořád vnímány antropocentricky). Ale lze to najít i u nemrtvých nebo nág. Prostě nenajdete Lidský kopiník - Lidský oštěpař, ale jen Kopiník - Oštěpař. Takže se i v jednotlivých liniích jednotky občas vůbec nejmenují sjednoceně nebo soudržně.

**Comment by hrubymar10** [comment]
> Jen nerozumím tomu, Martine, jak to s přítelkyní myslíte, když se jí nelíbí vazba a vám kouká asociace. Rád bych to pochopil, než začnu něco měnit.

Pointa je taková, že po laika jsou wose a ent jedno a to samé, ale pro lidi znalejší Tolkiena to neplatí. S velkou nadsázkou můžeme tvrdit, že psi a kočky jsou to samé. Sdílí přece vlastnost, že mají srst a mají čtyři nohy. No ale tím to vpodstatě končí...

U wosů a Entů sdílí vlastnost, že vychází ze stromů, jsou staří (teda wesnothský wose připouští i mladší exempláře) a mají schopnost mluvit. Ale tím jsme asi vyčerpali zásobu podobností.

* Ent má rozdělené končetiny. Má jasně patrné a popsané 2 nohy a má i 2 ruce. Wose je “jen” strom.
* Ent má díky končetinám možnost brát “lidi” (hobity) na svá ramena a přenášet je. Wose i kvůli absenci rukou ne.
* Charakteristika útoku se liší. Ent útočí tím, že kolem sebe máchá rukama a demoluje na co příjde. Wose útočí trochu jako Obelix (z komixů Asterix a Obelix) kdy k něčemu příjde a tím že je velký, silný a nezastavitelný, tak tím prostě projede, nebo jakoby vypne hruď (břicho) což způsobí odmrštění protivníka.

Abych to zakončil. To co jsem napsal není lobování za “Stromora” nebo lobování za nový jiný název. Je to vysvětlivka k tomu, co jsem napsal předtím a možná je to také zajímavý námět k zamyšlení pro podobné “překladatelské oříšky” v budoucnu, že by jsme neměli vždy vše házet do stejného pytle.

A jinak jsem samozřejmě pro změnit všechny výskyty Wosů na to, na čem se nakonec dohodneme.

**Comment by celerini** [comment]
Septime, souhlasím s tím, že jednotky není třeba vždy překládat jednotně. Smyslem založení této issue bylo upozornit na chybu a sjednotit dva různé překlady stejné jednotky Wose Sapling. Změnil jsem ve stabilní větvi TRoW Semenáčka na Sazenka, čímž považuji tuto záležitost za vyřízenou.

Martine, díky za odpověď. A díky oběma za souhlas se změnou. Po zralé úvaze jsem se rozhodl s překladem všech Wose počkat. Pokud k tomu budete chtít něco dodat, založte prosím novou issue.
