### ISSUE TITLE
scorpion

### ISSUE THREAD

**Issue by celerini** [hrubymar10/wesnoth-cs#237]
Narazil jsem při pokusu o dokončení překladu wesnoth-units na něco, co považuji za chybu a co mi brání překlad správně dokončit. Zároveň mám už dlouho poznamenáno nejednotné používání slova škorpion, které bych po odsouhlasení zároveň také rád odstranil.

Scuttler je z mého pohledu varianta škorpiona, ne krab. O tom svědčí umístění pod adresářem scorpion v datech hry, pod obřím škorpionem v nápovědě a také obrázky a animace, které jsou bez výjimky s dlouhým zadečkem ukončeným ostnem.

Slovo škorpion se ve hře vyskytuje i ve tvaru škorpi<b>ó</b>n, mám za to, že bychom měli používat jen jeden tvar.

Takže bych rád všechny scorpions přeložil jako štíry, škorpioně jako štírka. Sand scuttler by mohl být písečný štír, kdyby slovo scuttler nebylo uvedeno i jako varianta štíra. Proto navrhuji přeložit scuttler jako cupkal, cupkal písečný (cupkoun, cupal, cupoun).

Jako výhodu vidím, že štír je podle mých zkušeností používanější, více české slovo, které je navíc kratší, takže v panelu vpravo zabere méně místa a každá odvozená jednotka tam tak bude mít úplný popis.

@MultiSeptim, co ty na to?

**Comment by MultiSeptim** [comment]
Obecně souhlasím, opravdu to tak bude lepší. Tedy nevím, kde jsi vzal slovo cupkal, ale líbí se mi.

**Comment by celerini** [comment]
Díky za odsouhlasení.

Vzal jsem ho ve [slovníku](https://slovnik.seznam.cz/preklad/anglicky_cesky/scuttle) - tedy pokud jsem to nezvrzal, tak beru, že scuttler je podle toho, jak chodí (cupitá), třeba jako [scuttle fly](https://en.wikipedia.org/wiki/Megaselia_scalaris). Pak jsem vybral slovo, které nebylo moc zdrobnělé, když to je monstrum, a které by mohlo připomínat chození. Jestli se pletu, prosím o opravu.
