### ISSUE TITLE
DeepL fuzzies

### ISSUE THREAD

**Issue by celerini** [hrubymar10/wesnoth-cs#250]
Dal jsem dohromady takové udělátko, které jedním příkazem přeloží pomocí DeepL nepřeložené zprávy v .po souboru a označí je jako fuzzy (neúplný překlad).

Takhle to dopadlo u [DiD](https://github.com/hrubymar10/wesnoth-cs/commit/92341ef0aba86391637a69408084540506304bd2) a [tools](https://github.com/hrubymar10/wesnoth-cs/commit/1029ad80ffb21aee412c04095484670cd22b7c53).

Nabízím, že takhle neúplně přeložím WoF nebo jiný .po soubor.

Jen je třeba vzít v úvahu, že neúplné (fuzzy) překlady zpráv pak mohou být tří druhů - změny v originále, nové zprávy, které se podobají už přeloženým, nebo přeložené pomocí DeepL.

**Comment by MultiSeptim** [comment]
Aha, na tohle jsem nějak zapomněl. Do hotových překladů to předpokládám nezasahuje? Nevím, jestli to u WoF ještě použijeme, ale jinak to úplně špatně na těch výsledcích nevypadá.
V Poeditu koukám, že je utilita Předpřeložit, kde si lze navolit stroj, co se má pokusit o překlad (je tam i DeepL), ale myslím, že se mi výsledky moc nelíbily. Tohle je lepší?

**Comment by celerini** [comment]
Ne, do hotových překladů to nezasahuje. Ani do fuzzy. Jen to z nepřeložených udělá fuzzy (neúplné).

Předpokládám, že moje udělátko není lepší. DeepL překlady do češtiny by měly být v obou nástrojích totožné (ve stejném čase, DeepL se pořád učí).

Dál předpokládám, že máš na rozdíl ode mne placený Poedit, protože já mám ve svém systému volně dostupný Poedit 3.3.2 a ten v Před-přeložit... žádnou volbu stroje nemá, tedy před-překládá pouze z překladové paměti. Poedit nepoužívám.

Protože ty DeepL už automaticky používat můžeš a další překladatele nemáme, navrhuji tuto záležitost uzavřít.

**Comment by MultiSeptim** [comment]
Já placenou verzi nemám. Myslel jsem, že jak tam volím stroj, tak to překládá. A teď koukám, že to není pravda, opravdu to bere jen z nějaké paměti a proto ne moc dobře.

**Comment by celerini** [comment]
Zkusil jsem DeepL na zbytek WoF a [tady je výsledek](https://github.com/hrubymar10/wesnoth-cs/commit/19dbd628319c04b06e5ef8e0f0fc21ce21893c03).

Pokud to chceš použít, dám to do hlavní větve. Jestli ne, zahodím to.

**Comment by MultiSeptim** [comment]
Asi se s tím dá pracovat. Nech to.

**Comment by celerini** [comment]
Přidal jsem to tedy do hlavní větve (master).
