### ISSUE TITLE
Elfí eskorta - nový návrh

### ISSUE THREAD

**Issue by MultiSeptim** [hrubymar10/wesnoth-cs#289]
U popisu elfí eskorty je v součastnosti tento text:

_There once was an elf by the name of Beirand, who set out on a journey to a distant land.
Thirteen days he rode, no rest did he take, ‘til a nymph’s abode he entered, ‘side a lake.
“Look there, Narya!” Came a cry of glee, “Do thee spy that yonder apple tree?”
The response, a neigh, she jumped with delight, then off she skipped in a canter spright.
Not a moment passed ‘ere a gusting blast, blew all around, an airy voice cast:
“Hold there, thee elf, this grove is mine — no fruit shall I yield you, nor your equine.”
Next came the reply, “Please grant us respite. Long have we travel’d; surely see thee our plight!”
“Fatigue, I perceive, that is your case, but to earn my grace, let’s have a race.”
To this, the rider did consent, and toward the tree, then off they went.
A howl, a rush, a flying gale, the wind left the rider back on its tail.
But in a flashing streak, a gallop sleek, horse and rider past the wind did barely squeak.
In augmented time, back and forth they sped, ‘til at last, fleet elf arrived ahead.
“Well done,” spake the spirit, as she blew in, “my grace I shall grant thee and all of your kin.”
Beirand and Narya thus took their leave, bearing evermore, the nymph’s reprieve._

_The truth of this tale, one can only surmise, but doubtless, Outriders the fastest do comprise._

A pak tento můj překlad:

_Byl kdysi jeden elf, co jméno Beirand měl, který na velkou cestu do dálav vyjel.
Bez spočinutí on tři a deset dní jel, než do přístřešku jezerní nymfy vešel.
„Podívej, Naryo!“ radostný výkřik zněl, „Také zde vidíš tu nádhernou jabloněl?“
Hned v odpověď ji dychtivou po boku měl, cvalem, však rozvážným, co nesetřel by pel.
Nedala mu čas, aby se rozseděl, než vzdušný její hlas se vůkol rozezněl:
„Mé je ovoce v háji, tak co bys elfe chtěl, snad by sis ty či kůň tvůj na ně nemyslel?“
Na to ji prosil on: „Odpočinek uděl. Naši sešlost cestou by i slepý viděl!“
„K únavě své sis svým činěním přišel. Závodit však musíš, bys mou milost našel.“
A vskutku se k tomu ten elfí jezdec měl, že ten závod od stromu ke stromu on jel.
Ač kvílící vichr mu kolem uší zněl, ocasu jeho koně se přece neudržel.
Jako v záblescích lehce on na koni jel, jako by cvalem svým ovládnout vítr chtěl.
Jel tak, že i čas tikati snad zapomněl, až nakonec se v cíli na místě prvním skvěl.
V hlase jejím pak tón ocenění zněl a svou milost dala i těm, co za bratry měl.
A když pak Beirand od Naryi odešel, stále si nesl milost, co u ní našel._

_O pravdivosti tohoto příběhu se lze už jen dohadovat, ale jeho poselství nejrychlejší jezdci elfích eskort bezpochyby stále naplňují._

Požádal jsem svou kamarádku básnířku, co dlouho žila v USA, zda by nezkusila navrhnout něco více rytmického a zakulaceného. Zde je její návrh:

_Byl kdysi jeden elf pod jménem Beirand znám 
Do zemí dalekých on vypravil se sám 
Jel dlouhých třináct dní, zrána i zvečera 
když spatřil rajský sad na březích jezera
I hned se radostně k své klisně naklonil
"Hej, Naryo, vidíš též tu skvostnou jabloni?"
Kobylka znavená vesele zaržála
za sladkým ovocem hned cvalem spěchala.
V ten moment rozezněl se vůkol přísný hlas:
"To ovoce je mé! Ne tobě napospas!"
"Měj trochu soucitu, únava zmáhá nás, 
přej lahodný nám plod a odpočinku čas!"
"Já vím, že v nohou máš, i tvůj kůň spoustu mil
Než přízeň svou ti dám, chci abys závodil!"
"Jak žádáš, nymfo má, jen zkus nás dohonit!"
Elf tryskem vyrazil k překrásné jabloni
A letěl nad zemí jak sokol podél skal
však vichr kvílící jej skokem předehnal 
Tak s větrem o závod duněla kopyta
Kdo v cíli bude dřív? Jen to se počítá!
Byl šílený to boj - Bairand uháněl dál 
až vítr zemdlelý na chvostu zanechal.
Pak nymfa uznale se jezdci ukloní 
"Bravo! Buď hostem mým! Jez z vzácných jabloní!"
Ať úctu moji zná celý tvůj elfí lid!
Ať hojnost okusí, kdykoliv bude chtít!_

_Bylo či nebylo? Každý dnes hádat smí!
Však nejhbitější vždy dosáhne vítězství._

**Comment by celerini** [comment]
Paráda, čte se mi to moc dobře. Sice tam chybí tvůj legrační pel a háj, ale nechybí mi tam tvůj asynchronní rytmus a el na konci, takže návrh s radostí zařadím tak, jak je, snad bych jen upravil pomlčky na en-dash a doplnil interpunkci tam, kde v originále je a v překladu chybí. Veliké díky kamarádce, zvedla laťku o pěkných pár čísel vysoko. Do poznámky nad zprávu bych jí rád přiznal autorství, pokud by nesouhlasila, tak bych alespoň citoval tvou poznámku o básnířce.

**Comment by tapikuv** [comment]
Naprostá bomba!

Oto 'tapik' Buchta, ***@***.***, http://tapikuv.blogspot.com


út 23. 7. 2024 v 23:59 odesílatel Michal Žejdl ***@***.***>
napsal:

**Comment by MultiSeptim** [comment]
Tak určitě interpunkci apod. upravit. Také bych určitě sloučil stávající dva řádky do jednoho, aby blok textu byl širší a méně dlouhý.

Jinak tedy je ráda, že se líbí a bude potěšena uvedením svého jména, které zní Lenka Bittová.

**Comment by celerini** [comment]
Tak jsem to přeplácnul. Ještě jsem opravil I hned na Ihned, Bairand na Beirand a posunul poslední ukončovací uvozovku o verš dál.

Jestli jsem něco zpackal, tak mne opravte, jinak je za mě možné tuto záležitost uzavřít.

Ještě jednou děkuji za krásný překlad a přeji Lence, ať se jí daří co možná nejlépe.
