### ISSUE TITLE
Whitefang

### ISSUE THREAD

**Issue by celerini** [hrubymar10/wesnoth-cs#30]
Septime, nepřímo jste mě upozornil na chybu, kterou jsem zanesl do DiD. Chtěl jsem ji tiše opravit, ale protože jste se do DiD právě opřel, volím tuto cestu, abych vás upozornil.

My Češi neříkáme horám tesák, ale Špičák (je to vlastní jméno - vizte Božídarský Špičák, Děčínský Sněžník). Volil jsem v DiD opis, abych zachoval název vrcholku, takže já bych to rád opravil na:

Bilý Špičák
hory Bílého Špičáku
skřeti z hor Bílého Špičáku
skřeti od Bílého Špičáku

Opravte mne, nechte mne to opravit nebo to prosím opravte.

**Comment by celerini** [comment]
v 1.14 [opraveno](https://github.com/hrubymar10/wesnoth-cs/commit/830f3b8261bacbc8312750a58df7c5eb3098263e)

**Comment by MultiSeptim** [comment]
Tak snad opraveno i v main.

**Comment by celerini** [comment]
díky
