### ISSUE TITLE
BW, YW, BF, AF

### ISSUE THREAD

**Issue by celerini** [hrubymar10/wesnoth-cs#34]
Při revizi Septimova příspěvku jsem narazil na zkratky letopočtů, do kteréžto oblasti jsem se dosud nepustil.

Teď jsem chvíli studoval a mám v tom celkem jasno.

BW (Before Wesnoth) - př. W. (před Wesnothem)
YW (Year of Wesnoth) - r. W. (rok Wesnothu)
BF (Before the Fall) - př. P. (před Pádem)
AF (After the Fall) - po P. (po Pádu)

Vycházím z toho, že se nejedná o názvy ér, které by měly mít počáteční písmeno velké. Tedy v originále se žádné takové názvy nevyskytují, až na jeden případ "After the Fall" v editoru, kde je ovšem velké A proto, že je na začátku.

Tímto žádám o schválení, abych se mohl pustit do ustálení překladu zkratek letopočtů. V opačném případě prosím o věcné protiargumenty, pokud možno doložené odkazy.

**Comment by MultiSeptim** [comment]
Kopíruji, co tekrát psal tapik do konference:

_Nenašel jsem to nikde jinak, tak to fčíl nadhazuji - YW, neboli Year of Wesnoth, bychom neměli používat. Taky běžně nepoužíváme BC či AD, ale LP, n.l. a před n.l.  Nemohu ale přijít na žádnou pěknou zkratku. Napadly mne tyto:
- R.W. či r.W. jako roku Wesnothu
- l.W. jako léta Wesnothu
- W.l. jako Wesnothského letopočtu
- k.W. jako království Wesnothského

Také by to šlo řešit opisem. Tak jak nemá zkratku mé oblíbené "po sputniku". Takže:
- od založení Wesnothu
- království či království Wesnotského

Také si to můžeme udělat úplně jinak, podle sebe. Třeba jak to má J.R.R.T. - První věk, druhý věk, třetí věk, čtvrtý věk. Teď mne
napadla další zkratka: VW - věku Wesnothu.

A nebo úplně vypustit, což bych asi nyní doporučoval. Co vy na to?_

**Comment by MultiSeptim** [comment]
Jinak mě se tvé navržené zkratky líbí. Akorát s těmi malými písmeny to nevypadá tak sexy.

**Comment by celerini** [comment]
díky za příspěvek

předkládám tedy ke schválení podle mne lepší

BW - př. w. l. (před wesnothským letopočtem)
YW - w. l. (wesnothského letopočtu)

v textu tedy třeba "... roku 161 w. l."

**Comment by hrubymar10** [comment]
Jo, toto je věc, ke které jsem se nikdy neodhodlal. Přál bych si, aby bylo možné mít ty zkratky ve stejném formátu jako je originál, tj. AF -> PP (Po Pádu) . Problém je, že je to je jazykově špatně 😔 

Konkrétní překlady (neřešme teď jejich formát) jaké bych podpořil:

* BW (Before Wesnoth) - před Wesnothem
* YW (Year of Wesnoth) - roku Wesnothského
* BF (Before the Fall) - před Pádem
* AF (After the Fall) - po Pádu

**Comment by celerini** [comment]
Termíny "Before Wesnoth", "Year of Wesnoth", "Before the Fall" a "After the Fall" se, až na výše zmíněnou výjimku, v textu originálu nevyskytují, takže je není třeba překládat. Jsou pouze v poznámkám ke zkratkám, abychom věděli, co ty zkratky znamenají.

Samotné zkratky BW, BF a AF se také v textu originálu nevyskytují. Oproti tomu zkratka YW je využita celkem hojně.

Smyslem mého snažení je najít správnou českou zkratku pro YW tak, aby se dala použít na všech místech, kde ji používá originál (tedy nejen v tipech, denících a  letopisech, ale i v obyčejných sděleních). Mám za to, že jsem ji díky Septimově citování tapika už našel - tedy w. l. (wesnothského letopočtu).

Hráči, kteří znají zkratku [našeho letopočtu](https://cs.wikipedia.org/wiki/N%C3%A1%C5%A1_letopo%C4%8Det), by neměli mít při luštění w. l. větší potíže.

Zároveň se vyhneme tomu, abychom překladatele naváděli k chybám typu "roku 961 r. W." (stejná chyba s opakováním slova ze zkratky jako v případě LED dioda) a ty, kterým na tom záleží, nutili používat opis bez zkratky.
