### ISSUE TITLE
there is a new cs.po for DiD at wesnoth/wesnoth 1.14

### ISSUE THREAD

**Issue by celerini** [hrubymar10/wesnoth-cs#4]
Most of the begining of DiD in Fedora 29 (1.14.7) is in English.

I would like to start the corrections.

Can you pull it to the hrubymar10/wesnoth-cs or should I make a PR for whole file?

**Comment by hrubymar10** [comment]
I'll sync .po files with master now.

You can create PR then.

Also, I'll add you to the README file, if you won't be against it.

**Comment by hrubymar10** [comment]
It is synced now.

Closing by fcfce9a5b408b025735042089974b27d4c9a8f30
