### ISSUE TITLE
Nagini

### ISSUE THREAD

**Issue by MultiSeptim** [hrubymar10/wesnoth-cs#41]
Potřebujeme dořešit ty ženské od nág.
Při překládání Units na to opakovaně narážíme. Padly návrhy jako - nágina, nágyně nebo nechat i v ženském rodě nágy a přechylovat jen přízviska (nága bojovnice).
Všechny tři možnosti považuji za hodnotné (rozhodně lepší než nagini) a nejvíc se mi líbí nágyně nebo přechylování přízvisek.

**Comment by celerini** [comment]
Asi jsem to [začal já, ale to jsem ještě neměl jasno](https://github.com/hrubymar10/wesnoth-cs/pull/9#discussion_r499276890).

Před pár dny [jsem si to ujasnil](https://github.com/hrubymar10/wesnoth-cs/pull/39#pullrequestreview-518403845) a od té doby ať to beru z kterékoli strany, tak mi přijde, že je to ono.

Tedy **nepřechylovat**, použít slovo nága.

Proč?

- není to potřeba - Nagini se vyskytuje 1x v help (nevím kde) a pak jen v názvech jednotek. V angličtině nepoužívají **fightress**, tak mají Nagini. My ale máme bojovnici, takže nepotřebujeme mít i nága přechýlené (navíc používáme v popisu jednotek nágy podle vzoru ženy, takže toho ženského je tam víc než dost). Pokud by se někdy objevila v textech tažení dvojice nág různých pohlaví, tak věřím, že by dostala vlastní jména (zase to nebude potřeba)

- přechylovat se vždy nemusí - k nágám mají blízko hadi a ti také nemají hadice

**Comment by MultiSeptim** [comment]
Kdo to tedy upraví?
