### ISSUE TITLE
Heals +X apod.

### ISSUE THREAD

**Issue by MultiSeptim** [hrubymar10/wesnoth-cs#92]
Budeme se muset nějak poprat s netypickými hodnotami u léčení, případně regenerace . Zatím platilo, že heals +4 = ošetření, heals +8 = léčení a regenerates +8 = regenerace. Ale už se v mainline začínají objevovat jiné hodnoty (i když zatím v podstatě jen v UtBS a pouštních lidí). Tak jako tak se to nějak řešit musí.

Vidím dvě možné cesty (a případně nějakou kompromisní kombinaci):
1) Unifikovat vše na léčení a zakomponovat tam nějak číslovku. Výhodou je universálnost v rámci všech možných rozšíření a to i do budoucna. Nevýhodou je určitá jazyková nehezkost či ošklivost.
2) Fixovat 4 a 8 jako základní hodnoty a hodnoty kolem nich označit vhodným přídavných jménem (snížení/zvýšené; povrchní/pronikavé; slabé/silné). Takže např. heals +12 by bylo pronikavé léčení. Výhodou je možnost to udělat jazykově krásně. Nevýhodou je zachování neuniverzálnosti použití (když bude +12 pronikavé, jaké bude případně se objevivší +16?) a také to, že nebude jasné, kde má vést linie mezi ošetřením a léčením (bude +6 pronikavé ošetření nebo povrchní léčení?).
3) Řešení, odvozené z řešení č. 2. Fixovat 4 a 8 jako maximální základní hodnoty a vytvořit nové maximální základní hodnoty (např. +12; +16; + 20 a +24), které bude mít také nějaké standardní názvy. Vše ostatní pak nazývat jako snížené/povrchní/slabé. Toto však zcela neřeší tu první nevýhodu, kterou může být to, že se v daném rozsahu objeví více nižších mezihodnot. Lze se jen spolehnout na to, že hodnoty budou vždy sudé a tak bude existovat jen jedna možná mezihodnota.

U regenerace by se to pak provedlo analogicky.

**Comment by celerini** [comment]
Považuji překlad heals +x na ošetření a léčení za (hezkou, ale přesto) chybu. Dosud mi nevadila asi proto, že jsem ještě nic pouštního nehrál.

Přidal jsem tedy commit, který mění jen fuzzy (nové) na to, co by tam podle mého mělo být. Místo léčí +x by mohlo být i méně používané hojí +x (k čemuž by pak patřil i třeba nějaký ten ranhojič).

K tomu zhezčování pomocí přídavných jmen snad jen tolik - představte si, že se v rámci vývoje vymění pevná čísla +4, +8, +12 za proměnné. Pak budeme v loji úplně. Pokud skutečně věříte na vylepšování, pak myslím, že ta správná cesta je vylepšit to ve hře (což může každý - vy i já) a pak to přeložit (ne řešit ošklivost hry překladem).

Sjednocení můžeme udělat později, protože to bude více práce s malým přínosem. Pro mne osobně to v tuto chvíli není na pořadu dne a komunita (hráči na Steam) si stěžovali na neúplný překlad, ne na takovéto podrobnosti.

**Comment by MultiSeptim** [comment]
Ošetření a léčení vzniklo před mnoha lety, kdy existovaly jen hodnoty 4 a 8 (a jiné se neobjevovaly ani v rozšířeních). Nevím, proč by to měla být chyba, snad proto, že se sloveso překládá podstaným jménem? Ale to plyne z toho, že to figuruje i jako název schopnosti.
A nevím, jestli jsem vůbec dobře pochopil celý tvůj komentář. Jakože preferuješ do budoucna řešení č. 1? A čeho se týká ta poznámka o vylepšování ve hře (je to to sloveso jako název schopnosti)?
Jinak já se samozřejmě přikláním k univerzálnějšímu řešení (č. 1) s číslovkami...

**Comment by celerini** [comment]
Chyba je to pro mne ze dvou důvodů:
1. Ano, sloveso bych překládal slovesem, protože jedna zpráva se může objevit na více místech. Například zde
![jesteracky_vestec](https://user-images.githubusercontent.com/37598370/103202969-2da5e900-48f4-11eb-86c8-4a8a29bf84be.png)
se mi dobře čte chaotický, rychlý a silný (v duchu si doplním slovo **je**), ale ošetření pak vyčuhuje (v duchu si musím vybavit, že se jedná o schopnost, která se tak jmenuje, tedy doplňuji slova **má schopnost**). Když tam bude léčí +4, tak není co dodat (doplňovat). Oproti tomu v seznamu schopností v nápovědě skousnu, když bude [ve shodě s předlohou](https://github.com/wesnoth/wesnoth/blob/master/data/core/macros/abilities.cfg) obsahovat i slovesa nebo třeba přídavná jména (do nápovědy se tak často nedívám).
2. Slovo ošetření neobsahuje informaci (číslo), jak moc mi přidá života. Musím se to naučit a pamatovat si to, nebo si to vybavit. Je to složitost navíc, která ztěžuje používání hry, a je to vlastnost překladu, ne hry samotné.

Ano, dávám přednost použití čísel z předlohy.

Ne, poznámku o vylepšování jsem myslel tak, že pokud vám například vadí čísla a vidíte za přínosné vymyslet systém jejich slovního pojmenování, pak byste se měl pokusit to prosadit do hry, aby z vašeho dobrého nápadu měli užitek všichni hráči. Pokud si dovolím srovnání, tak nehledat s [Felixem aluminiovej klíček](https://www.youtube.com/watch?v=RIGIs5zRqy4) tam, kde je větší světlo, ale tam, kde byl ztracen.

**Comment by MultiSeptim** [comment]
OK.
Samozřejmě to nemusíme dolaďovat teď. Ale v budoucnu (až se budem blížit 100 %) už bude aspoň jasné, jakým směrem jít.

**Comment by MultiSeptim** [comment]
Tak bychom to mohli teď dořešit.
Navrhuji všude sjednotit na léčí +X (resp. léčení, kde se to objevuje ve tvaru podstatného jména) a regeneruje +X (resp. regenerace). Dal bych přednost regeneruje a ne obnovuje, protože je to víc fantasy.

**Comment by celerini** [comment]
Souhlasím se změnou.

Jen teď dávám přednost dotažení překladu na 100 %, takže pokud chcete, je to na vás, pokud ne, mám to v poznámkách na později.

**Comment by MultiSeptim** [comment]
Já bych to asi neuměl nějak hromadně. Jsem ochoten se to naučit, ale musel by mi někdo poradit.

**Comment by celerini** [comment]
V tomto případě to nevypadá na hromadnou změnu, protože základ (heals +) je, dobře a správně, uveden jen jednou (v doméně **help**), spíš na citlivé projití a opravy. Například tam, kde se heals +4 překládá jako ošetření.

Dívám se teď ve svém systému Linux příkazem **grep**, který hledá výskyty výrazů v souborech. Následující příkaz mi vypíše všechny soubory (-l), ve kterých se vyskytuje regulární výraz (-E) a nezáleží na velikosti písmen (-i). Regulární výraz vyjadřuje slova **heals** a **regenerates**:

grep -Eil "(heal|regenerate)s" *.po
wesnoth-did.po
wesnoth-help.po
wesnoth-low.po
wesnoth-manual.po
wesnoth.po
wesnoth-tb.po
wesnoth-tutorial.po
wesnoth-utbs.po

Když se na to podívám podrobněji (bez -l, to se vypíšou řádky, které daný výraz obsahují) a přidám i výsledek příkazu **grep -i ošetření**, tak to vypadá, že opravit je třeba hlavně domény **help**, **manual** a **tutorial**.

**Comment by MultiSeptim** [comment]
Zkontrolováno vše, kromě help, manual a tutorial.

**Comment by MultiSeptim** [comment]
Tak jsem dokončil i tyto tři domény. Až se všechny PR vyřeší, můžem to tu zavřít.

**Comment by MultiSeptim** [comment]
Teď jsem se ještě díval, jak to vypadá ve hře. A bohužel ten slovesný tvar nemusí vždy vypadat dobře. U jednotek ano, ale v samotném helpu ne.
![heal](https://user-images.githubusercontent.com/71945783/116158331-c572e280-a6ee-11eb-9c03-44ecf2f078b0.jpg)
Jiné schopnosti třeba také nejsou ve tvaru slovesa, a kdyby měly být, tak by nám z toho vyšel dvouslovný tvar (např. skrývá se).
Dále je to pak ještě někdy prolinkováno na texty o léčení, což také nevypadá dobře. Asi bych ještě dodatečně navrhoval změnit léční na léčení a regeneruje na regeneraci. Jde v podstatě jen o pár řetězců v help.

**Comment by celerini** [comment]
Mě to v nápovědě neruší. Help není samotný (určující), je podřízený hře - hra tu není pro nápovědu, ale nápověda pro hru. Nenechte se mýlit tím, že řetězce **heals** jsou součástí domény help.

Považuji za svoji osobní chybu a selhání, že jsem vám to pustil v manuálu.

Ano, myslím, že **skrývá se** je lepší než **skrývání**. Dvouslovný tvar není překážkou. Krom podstatných jmen a sloves tam vidím i přídavné jméno **steadfast** - opět mi přijde **nezlomný/nezlomná** mnohem lepší než **vytrvalost**.

S návrhem udržovat v rozporu s předlohou jednu stránku v nápovědě tak, aby obsahovala výčet podstatných jmen, nesouhlasím.

**Comment by MultiSeptim** [comment]
Prostě mi to přijde, že originál jde ošklivosti naproti. Takový mix různých slovních druhů zákonitě musí vést k více či méně nehezkým tvarům v překladech (a myslím tím i jiné překlady než evropské) nebo k různým jazykovým kompromisům.
Některé věci by zněly blbě i v češtině, třeba to steadfast. I když je tam i feminimní tvar, jak by to vypadalo v seznamu. Jako nezlomný/nezlomná? Nebo nezlomí se? A nebo třeba feeding. Pokud by se přeložilo jako krmí se, tak by mi to přišlo trochu hloupacaté (pocitová záležitost).
A také jsi nereflektoval na ty linky, které někdy vypadají blbě. Někde se mluví o něčem (ve tvaru podstatného jména) a pak to prolinkuje na sloveso, ačkoli je to textově odlehlé od jednotek a tak by se spíš zase hodilo pojednání ve jmenném tvaru.

Ale asi to tak jako tak přežiju. Jen bych to prostě chtěl mít perfektní ze všech stran.
Úplně nejlepší korektní řešení by bylo podle mě, kdyby se jeden tvar řetězce nepoužíval „všude”, ale kdyby systém dovedl řídit tvar kontextuálně. Ve smyslu jako je female^něco, tak by bylo noun^něco či verb^něco, jestli chápeš.

**Comment by celerini** [comment]
V seznamu by bylo jedno přídavné jméno pro mužský rod - tedy jedno z **vytrvalý**, **pevný**, **stálý**, **neochvějný**, **neotřesitelný** nebo **nezlomný**, abych citoval slovník. Bylo by to pak dobře přeložené a mně by to tak vyhovovalo.

Feeding je přeložené dobře, podstatným jménem slovesným, to neřeším.

Našel jsem (pro překlad) odkazy pouze ze stránky **Léčení**. Přechod regenerace -> regeneruje, léčení -> léčí mi nevadí, neruší mne, připadá mi v pořádku (odkaz není na slovní druh, ale na rozvedení významu, který reprezentuje). Navíc mlaskám blahem na automatickými odkazy ze stránek jednotek, tam mi současný stav přijde jako lepší předchozího.

Použití kontextu chápu, tak už je ten systém udělaný (že to dovede), ale uvedení kontextu záleží na tvůrcích předlohy, nikoli na nás překladatelích.
